# Generated by Django 2.2.12 on 2020-05-28 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_auto_20200528_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='anorder',
            name='auser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='anorder',
            name='items',
            field=models.ManyToManyField(blank=True, to='orders.OrderItem'),
        ),
        migrations.AddField(
            model_name='anorder',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='anorder',
            name='status',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
