# Generated by Django 2.2.12 on 2020-05-23 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200522_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pizza'), (2, 'Sicilian Pizza'), (4, 'Sub'), (6, 'Pasta'), (7, 'Salad'), (8, 'Dinner Platter')]),
        ),
    ]
